---
title: "model_development"
output: html_document
---


## Research Question 1: Dominant Species Shannons index of Diversity

  
















# Data
```{r}
# Use the choose files function to get the location of the datasets on your computer
# choose.files()

# Should get an output like:
# "C:\\Users\\Jacob\Project\\Data\\biotic_leaftraits.RData"

# Copy the folder spot below, and copy the """".RData file into the load function below

location <- "C:\\Users\\Jacob\\Dropbox\\Semester 2 2017\\MXB344\\Project\\Data\\"

# Load the datasets
load(paste0(location, "biotic_leaftraits.RData"))


```


## Number of Leaf Traits evident in each Quadrat
```{r}
leaf_trait_choice <- "leaf_arrangement"

for (leaf_trait_choice in names(biotic_leaftraits.df)[8:15]) {

count_data <- biotic_leaftraits.df %>%
  rename_("leaf_trait" = leaf_trait_choice) %>%
  group_by(site, leaf_trait) %>% # CHANGE LEAF TRAIT
  summarise(number_observations = n())%>%
  mutate(leaf_trait = ifelse(number_observations < 3, 
                             "Other (variety of uncommon)",
                             leaf_trait))  %>%
  arrange(desc(site), desc(number_observations)) %>%
  mutate(leaf_trait = factor(leaf_trait, 
                             levels = leaf_trait,
                             ordered = TRUE))

# CHANGE THE X VARIABLE LEAF TRAIT TO THE ONE ABOVE
p1 <- ggplot(aes(x=leaf_trait, y=number_observations, fill = site),
       data = count_data) + 
  geom_bar(stat = "identity", position = "dodge") +
  ggtitle(paste(leaf_trait_choice, "Comparison")) +
  theme_project() +
  scale_fill_manual(name = "Site", values = colours.site) +
  # coord_flip()
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1, vjust = 1)) +
  scale_y_continuous(breaks = seq(0, 30, 5)) +
  ylab("Number of Species") +
  xlab(leaf_trait_choice)

print(p1)
}

```


```{r}
leaf_trait_choice <- "leaf_arrangement"

count_data <- biotic_leaftraits.df %>%
  select(-transect, -quadrat) %>%
  distinct() %>%
  select(-dom_species_id, -species_name, -species_presence) %>%
  gather(leaf_trait, composition, -site, -species_id) %>%
  filter(leaf_trait != "other")

count_data %>%
  group_by(site, leaf_trait, composition) %>%
  summarise(obs = n()) %>%
  arrange(desc(obs)) %>%
  ggplot(aes(x = site, y = composition)) +
  geom_point() +
  facet_wrap("leaf_trait", scale="free_y")
  

# CHANGE THE X VARIABLE LEAF TRAIT TO THE ONE ABOVE
p1 <- ggplot(aes(y=leaf_trait, x=site, fill = site),
       data = count_data) + 
  geom_point()

print(p1)


```

```{r}
biotic_leaftraits.df %>%
  filter(!is.na(leaf_arrangement)) %>%
  ggplot(aes(x = av_trans_elevation, y = leaf_arrangement,
             col = site)) +
  geom_point() +
  theme_bw()

```

