---
title: "data_preparation"
output: html_document
---


```{r}
location <- paste0(data_folder, "Malaysia_Capstone_Raw_Data.xlsx")

sheets <- c("Transect", 
            "Quadrat", 
            "Species ID",
            "Leaf Traits",
            "Leaf Area", 
            "Dominant Leaf Area",
            "Seedling Count", 
            "Dominant Seedling Count",
            "Filter Paper", 
            "Canopy Cover", 
            "Hobo ID", 
            "Hobo Time Series",
            "Time Index",
            "Penetrometer")

dictionary <- read_excel(paste0(location), sheet = "Dictionary")
transect <- read_excel(paste0(location), sheet = "Transect")
quadrat <- read_excel(paste0(location), sheet = "Quadrat")
species_id <- read_excel(paste0(location), sheet = "Species ID")
seedling_count <- read_excel(paste0(location), sheet = "Seedling Count")
dom_seedling_count <- read_excel(paste0(location), sheet = "Dominant Seedling Count")
leaf_traits <- read_excel(paste0(location), sheet = "Leaf Traits")
leaf_area <- read_excel(paste0(location), sheet = "Leaf Area")
dom_leaf_area <- read_excel(paste0(location), sheet = "Dominant Leaf Area")
filter_paper <- read_excel(paste0(location), sheet = "Filter Paper")
canopy_cover <- read_excel(paste0(location), sheet = "Canopy Cover")
hobo_id <- read_excel(paste0(location), sheet = "Hobo ID")
hobo <- read_excel(paste0(location), sheet = "Hobo Time Series")
hobo_index_time <- read_excel(paste0(location), sheet = "Hobo Index Time")
penetrometer <- read_excel(paste0(location), sheet = "Penetrometer")
```

```{r species_id_presence}
# transect dataframe contains elevation information
# get average elevation of each 
# Is this a modelling variable?
transect2 <- transect %>%
  group_by(Site, Transect) %>%
  summarise(av_trans_elevation = mean(Elevation))

# quadrat dataframe contains quadrat coordinates, and does not provide any modelling information
# It contains all quadrats as rows, and is useful as a base dataset to join information to
quadrat2 <- quadrat %>%
  select(Site, Transect, Quadrat)

# species_id dataframe is only used for combining a name to each species ID
# This does not get included in the modelling dataframe
# This is used as a look up table for exploratory analysis
# Jenn and Mimi's presence data now lets us include species richness into out dataset
# Only for 12 quadrats
# Valid for 12 quadrat and species ID level
species_id2 <- species_id %>%
  filter(!is.na(`Species ID`)) %>%
  gather(site_trans_quad, Presence, -`Species ID`, -`Dom Species ID`, -`Species Pseudo Name`) %>%
  mutate(Site = substr(site_trans_quad, 1, 1),
         Transect = as.numeric(substr(site_trans_quad, 4, 4)),
         Quadrat = as.numeric(substr(site_trans_quad, 7, 7))) %>%
  select(-site_trans_quad) %>%
  rename(species_presence = Presence)

# So, we have our research question 3 dataset started below
species_id3 <- species_id2 %>%
  group_by(Site, Transect, Quadrat) %>%
  summarise(species_richness = sum(as.numeric(species_presence)))
```

```{r seedling_abundance_cover}
# seeling_count dataframe contains the count of every species found in the quadrats (Jenn and Mimi)
# this needs to be grouped to a species ID level
# This data was discontinued from day 1 - obselete for modelling, however it is interesing to look at for the 5 quadrats analysed
seedling_count2 <- seedling_count %>%
  group_by(Site, Transect, Quadrat, `Species ID`) %>%
  summarise(day1_abundance = n(),
            day1_av_height = mean(`Height (cm)`))

# quadrat_seedling_count2below verifies that the Species Richness data in species_id3 is equivalent to what was collected on Day 1
# We want to get richness and abundance at a quadrat level
quadrat_seedling_count2 <- seedling_count2 %>%
  ungroup() %>%
  group_by(Site, Transect, Quadrat) %>%
  summarise(day1_richness = n(),
            day1_abundance = sum(day1_abundance),
            day1_av_height = mean(day1_av_height))
  

# dom_seedling_count dataframe contains the count and seedling over (for each dom species and overall).
# this is already grouped to a species ID level, so we remove unnecessary columns
dom_seedling_count2 <- dom_seedling_count %>% 
  select(-Date, -Day, `Data Back Up Photo`) %>%
  left_join(species_id %>% select(`Species ID`, `Dom Species ID`),
            by = "Dom Species ID")

specieslvl_dom_seedling_count2 <- dom_seedling_count2 %>%
  rename(dom_abundance = `Dom Species Abundance`,
         dom_seedling_cover = `Dom Seedling Cover`,
         overall_seedling_cover = `Overall Seedling Cover`) %>%
  select(-`Data Back Up Photo`)

# we want to use this dominant species information at q quadrate level, so we calculate simpsons index of diversity (1 - D) and shannons index
simpcalc_total <- dom_seedling_count2 %>%
  group_by(Site, Transect, Quadrat) %>%
  summarise(dom_total_abundance = sum(`Dom Species Abundance`)) %>%
  mutate(simpcalc_denominator = dom_total_abundance*(dom_total_abundance-1))
  
simpcalc_individual <- dom_seedling_count2 %>%
  group_by(Site, Transect, Quadrat) %>%
  mutate(n_times_n_1 = `Dom Species Abundance`*(`Dom Species Abundance`-1)) %>%
  summarise(simpcalc_numerator = sum(n_times_n_1))
  
simpson_calculation <- simpcalc_individual %>%
  left_join(simpcalc_total, by=c("Site", "Transect", "Quadrat")) %>%
  mutate(dom_simpson = 1-(simpcalc_numerator/simpcalc_denominator)) %>%
  select(-simpcalc_numerator, -simpcalc_denominator)

shannon_calculation <- dom_seedling_count2 %>%
  group_by(Site, Transect, Quadrat) %>%
  mutate(p = as.numeric(`Dom Seedling Cover`)/100,
         lnp = -log(p),
         shannon_calc = p*lnp) %>%
  summarise(dom_shannon = sum(shannon_calc, na.rm = TRUE),
            dom_total_seedling_cover = sum(`Dom Seedling Cover`, na.rm=TRUE),
            overall_seedling_cover = first(`Overall Seedling Cover`)/100)

quadrat_dom_seedling_count2 <- simpson_calculation %>%
  left_join(shannon_calculation, by=c("Site", "Transect", "Quadrat"))
```

```{r leaf_traits}
# leaf_traits dataframe contains the leaf trait descriptions of every species identified by Mimi and Jenn, and Sasha and Shan on day 1
# This information is important to see if there is a higher tendency for certain leaf traits (ovulate being most common Apex for all species) in this rainforest compared to other rainforests
# This information is already at a species ID level, so it will be joined onto the species_modelling.df

leaf_traits2 <- leaf_traits %>%
  rename(leaf_arrangement = `Leaf Arrangment`,
         leaf_organisation = `Leaf Organisation`,
         leaf_shape = `Leaf Shape`,
         apex_shape = `Apex Shape`,
         base_shape = `Base Shape`,
         leaf_margin = `Leaf Margin`,
         secondary_venetion = `Secondary Venation`,
         tertiary_venetion = `Tertiary Venation`,
         other = Other)


```

```{r leaf_area}
# leaf_area dataframe contains the leaf area and dry weight from Mimi, Sasha and Shan's species data from Wednesday
# We want to get the average SLA on a species ID level
# The dry weights are not available, so this data is obsolete

# dom_leaf_area dataframe contains the 5 leaf samples of each dominant species, and the total weight of all 5 leaves (for each quadrat)
# this needs to be grouped to a species ID level

dom_leaf_area2 <- dom_leaf_area %>%
  filter(is.na(Unuseable)) %>%
  group_by(Site, Transect, Quadrat, `Dom Species ID`) %>%
  mutate(av_dom_leaf_dry_weight = `Total Dom Leaf Dry Weight`/`Dom Leaf Count`) %>%
  rename(total_dom_leaf_dry_weight = `Total Dom Leaf Dry Weight`)

dom_leaf_area3 <- dom_leaf_area2 %>%
  select(Site, Transect, Quadrat, `Dom Species ID`, `Dom Leaf Area 1`, `Dom Leaf Area 2`,
         `Dom Leaf Area 3`, `Dom Leaf Area 4`, `Dom Leaf Area 5`, `Dom Leaf Area 6`, 
         av_dom_leaf_dry_weight, total_dom_leaf_dry_weight) %>%
  gather(sample, leaf_area, -Site, -Transect, -Quadrat, -`Dom Species ID`, -av_dom_leaf_dry_weight, -total_dom_leaf_dry_weight) %>%
  mutate(dom_sla = leaf_area/av_dom_leaf_dry_weight) %>%
  ungroup() %>%
  filter(!is.na(leaf_area)) %>% 
  left_join(species_id %>% select(`Species ID`, `Dom Species ID`), by="Dom Species ID") %>%
  arrange(Site, Transect, Quadrat, `Dom Species ID`) %>%
  select(Site, Transect, Quadrat, `Dom Species ID`, dom_sla, leaf_area, av_dom_leaf_dry_weight, total_dom_leaf_dry_weight, `Species ID`)

# Check for balance of dataset
# specieslvl_dom_leaf_area2 %>%
#   group_by(Site, Transect, Quadrat, `Dom Species ID`) %>%
#   summarise(obs = n()) %>%
#   arrange(desc(obs))

# Some doubled up measurements.. not sure if any are incorrect
# The disturbed double up occur from the 3 3* labelling issue. COrrected now in raw data
# Assumption is that the Pristine was meant to be Quadrat 2
# specieslvl_dom_leaf_area2 %>%
#   filter((Site == "D" & Transect == 2 & Quadrat == 3 & `Dom Species ID` == 2) |
#            (Site == "D" & Transect == 2 & Quadrat == 3 & `Dom Species ID` == 3) |
#            (Site == "P" & Transect == 1 & Quadrat == 1 & `Dom Species ID` == 3))

# Now get a unique species lvl dataset
specieslvl_dom_leaf_area3 <- dom_leaf_area3 %>%
  group_by(Site, Transect, Quadrat, `Dom Species ID`) %>%
  summarise(total_dom_leaf_area = sum(leaf_area),
            total_dom_leaf_dry_weight = sum(total_dom_leaf_dry_weight),
            av_dom_sla_from_ind = mean(dom_sla)) %>%
  mutate(av_dom_sla_from_total = total_dom_leaf_area/total_dom_leaf_dry_weight)

# Get the quadrat level dataset
quadrat_individ_dom_sla <- specieslvl_dom_leaf_area3 %>%
  mutate(species_sla = paste0("av_dom_", `Dom Species ID`, "_sla")) %>%
  ungroup() %>%
  select(Site, Transect, Quadrat, species_sla, av_dom_sla_from_ind) %>%
  spread(species_sla, av_dom_sla_from_ind) %>%
  group_by(Site, Transect) %>%
  mutate(av_dom_1_sla = ifelse(is.na(av_dom_1_sla),
                            mean(av_dom_1_sla, na.rm = TRUE),
                            av_dom_1_sla)) %>%
  mutate(av_dom_2_sla = ifelse(is.na(av_dom_2_sla),
                            mean(av_dom_2_sla, na.rm = TRUE),
                            av_dom_2_sla)) %>%
  mutate(av_dom_3_sla = ifelse(is.na(av_dom_3_sla),
                            mean(av_dom_3_sla, na.rm = TRUE),
                            av_dom_3_sla))


# Now get a dataset at quadrat level
quadrat_dom_leaf_area3 <- dom_leaf_area3 %>%
  group_by(Site, Transect, Quadrat) %>%
  summarise(total_dom_leaf_area = sum(leaf_area),
            total_dom_leaf_dry_weight = sum(total_dom_leaf_dry_weight),
            av_totaldom_sla = mean(dom_sla)) %>%
  left_join(quadrat_individ_dom_sla,
            by = c("Site", "Transect", "Quadrat"))

# There is one stupid sla value.. investigae why
# dom_leaf_area %>% 
#   filter(Site == "P", Transect == 2, Quadrat == 5) %>%
#   t()
# 
# dom_leaf_area2 %>% 
#   filter(Site == "P", Transect == 2, Quadrat == 5) %>%
#   t()
# Since there is no leaf dry weight, it needs to be excluded
# And the weight of 0.005 (< 0.01) is unreadable from the scale and produces an SLA of 234.. unreliable data and is excluded
# It is filtered out in the datastep above. Remove the filter 'filter(is.na(Unuseable))' if you want to see the values

```

```{r soil_abiotic}
# filter_paper dataframe contains the decomposition data for each transect. Group to a transect level the average decomposition
filter_paper2 <- filter_paper %>%
  group_by(Site, Transect) %>%
  filter(is.na(Eaten)) %>%
  mutate(decomposition = (`Initial Weight`-`Dry Weight`)/`Days in Ground`) %>%
  select(Site, Transect, decomposition) %>%
  filter(!is.na(decomposition))

transect_filter_paper2 <- filter_paper2 %>%
  summarise(av_trans_decomposition = mean(decomposition, na.rm=TRUE))

# canopy_cover dataframe contains the LAI and the subjective weather conditions. If there are overlaps between weather and quadrats, we can test for a difference in LAI.
# LAI is highly variable though...

# canopy_cover %>%
#   group_by(Site, Transect, Quadrat, Weather) %>%
#   summarise(av_lai = mean(LAI)) %>%
#   select(Site, Transect, Quadrat) %>%
#   table()
# quadrat 1 and 2 in Pristine Transect 1 have two measurements

# canopy_cover %>%
#   group_by(Site, Transect, Quadrat, Weather) %>%
#   summarise(av_lai = mean(LAI), time = first(`Time Canopy Cover`), day = first(Day)) %>%
#   filter(Site == "P", Transect == 1, Quadrat %in% c(1,2))
# So the cloudy days at ~10am have a higher LAI than Sunny days at 1pm... interesting

# Anyways, group to quadrat level the average LAI. No lai data is available for Disturbed Transect 2 or 3
# LAI will need to be imputed for total analysis, ut results are skeptical
canopy_cover2 <- canopy_cover %>%
  rename(lai = `Leaf Area Index`, gft = `Gap Fraction Threshold`) %>%
  select(Site, Transect, Quadrat, lai, gft)

quadrat_canopy_cover <- canopy_cover2  %>%
  group_by(Site, Transect, Quadrat) %>%
  summarise(av_quad_lai = mean(lai), av_quad_gft = mean(gft)) %>%
  ungroup()

transect_canopy_cover2 <- canopy_cover2  %>%
  group_by(Site, Transect) %>%
  summarise(av_trans_lai = mean(lai), av_trans_gft = mean(gft)) 


# impute LAI: Get average of disturbed LAI
disturbed_mean_lai <- canopy_cover2 %>% 
  select(Site, lai) %>%
  filter(Site == "D") %>% 
  distinct() %>%
  summarise(mean = mean(lai, na.rm = TRUE)) %>%
  unlist(use.names = FALSE)

disturbed_mean_gft <- canopy_cover2 %>% 
  select(Site, gft) %>%
  filter(Site == "D") %>% 
  distinct() %>%
  summarise(mean = mean(gft, na.rm = TRUE)) %>%
  unlist(use.names = FALSE)

imputed_cc <- data.frame(Site = rep("D", 10),
                         Transect = c(rep(2, 5), rep(3, 5)),
                         Quadrat = rep(1:5, 2)) %>%
  data.frame() %>%
  tbl_df() %>%
  mutate(av_quad_lai = disturbed_mean_lai,
         av_quad_gft = disturbed_mean_gft,
         Site = as.character(Site),
         Quadrat = as.numeric(Quadrat))

quadrat_canopy_cover2 <- rbind(quadrat_canopy_cover,
                               imputed_cc) %>% 
  tbl_df()

# penetrometer dataframe contains the soil compaction measurements. 
# The extra 8 measurements throughout the transect should be investigated separately,
# However they are fitlered out of the quadrat level data 
penetrometer2 <- penetrometer  %>%
  rename(compaction = Compaction) %>%
  select(Site, Transect, Quadrat, compaction) %>%
  mutate(Quadrat = as.numeric(Quadrat))

quadrat_penetrometer2 <- penetrometer2 %>%
  group_by(Site, Transect, Quadrat) %>%
  summarise(av_quad_compaction = mean(compaction))

transect_penetrometer2 <- penetrometer2 %>%
  group_by(Site, Transect) %>%
  summarise(av_trans_compaction = mean(compaction))
```

```{r hobo_cleaning_data}
# hobo_id dataframe contains the start and end times for the Hobo times series data
# hobo dataframe contains the times series data for temperature and relative humidity
# THere is a ten hour lag in datetime to min/max time (min time in future)..
min_time <- as.POSIXct(strftime("2017-09-26 10:00:00", "%Y-%m-%d %H:%M:%S")) #midnight on the 26th
min_new_time <- as.POSIXct(strftime("2017-09-28 03:00:00", "%Y-%m-%d %H:%M:%S"))
max_time <- as.POSIXct(strftime("2017-09-28 22:00:00", "%Y-%m-%d %H:%M:%S"))


# Group this to a transect level
hobo_nofilter <- hobo %>%
  left_join(hobo_index_time, by="Index") %>%
  left_join(hobo_id, by=c("Hobo ID")) %>%
  filter(Time > `Hobo Start Time`, Time < `Hobo End Time`) %>%
  rename(hobo_id = `Hobo ID`, temp = Temperature, index = Index,
         rel_humid = `Relative Humidity`, date_time = Time,
         start_hobo = `Hobo Start Time`, end_hobo = `Hobo End Time`) %>%
  select(-`Data Back Up Photo`, -`Time Hobo`, -index) %>%
  arrange(hobo_id, date_time)%>%
  mutate(filter_minhobo = ifelse(!(hobo_id %in% c("3", "8", "13", "6")),
                                 min_new_time,
                                 min_time), 
         filter_maxhobo = max_time)


hobo2 <- hobo_nofilter 



max_min_hobo2 <- hobo2  %>%
  group_by(Site, Transect, hobo_id, start_hobo, end_hobo) %>%
  summarise(min_temp = min(temp),
            max_temp = max(temp),
            min_rel_humid = min(rel_humid),
            max_rel_humid = max(rel_humid))

# Create time series hobo dataframe, with min, mean, max variables


hobo3 <- hobo2 %>%
  filter(date_time >= filter_minhobo, date_time <= filter_maxhobo) %>%
  left_join(max_min_hobo2, by=c("Site", "Transect", "hobo_id", 
                                "start_hobo", "end_hobo")) %>%
  mutate(hobo_id = factor(hobo_id))

transect_hobo2 <- hobo2 %>%
  group_by(Site, Transect) %>%
  summarise(start_hobo = max(start_hobo),
            end_hobo = min(end_hobo),
            min_temp = min(temp),
            max_temp = max(temp),
            range_temp = max_temp - min_temp,
            min_rel_humid = min(rel_humid),
            max_rel_humid = max(rel_humid))  %>% 
  select(Site, Transect, min_temp, max_temp, range_temp) # The other variables are cr


```





<!--##########################################################-->
<!--##########################################################-->
<!--##########################################################-->
<!--      Now create the final datasets used for modelling    -->
<!--##########################################################-->
<!--##########################################################-->
<!--##########################################################-->
```{r biotic_dataframe}
biotic_leaftraits.df <- species_id2 %>%
  left_join(leaf_traits2,
            by = c("Species ID")) %>%
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(quadrat_penetrometer2,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  left_join(transect_hobo2,
            by = c("Site", "Transect"))%>%
  left_join(quadrat_canopy_cover2,
            by = c("Site", "Transect", "Quadrat")) %>%
  rename(species_id = `Species ID`, 
         dom_species_id = `Dom Species ID`,
         species_name = `Species Pseudo Name`,
         site = Site, transect = Transect,
         quadrat = Quadrat) %>%
  mutate(species_id = factor(species_id), 
         dom_species_id = factor(dom_species_id)) %>%
  filter(species_presence == 1) %>%
  select(-species_presence)

save(biotic_leaftraits.df, file = paste0(data_folder, "biotic_leaftraits.RData"))
```

```{r abiotic}
abiotic_penetrometer.df <- penetrometer2 %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat)

save(abiotic_penetrometer.df, 
     file = paste0(data_folder, "abiotic_penetrometer.RData"))

abiotic_canopycover.df <- canopy_cover2 %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat)

save(abiotic_canopycover.df, 
     file = paste0(data_folder, "abiotic_canopycover.RData"))

abiotic_filterpaper.df <- filter_paper2 %>%
  rename(site = Site, transect = Transect)

save(abiotic_filterpaper.df, 
     file = paste0(data_folder, "abiotic_filterpaper.RData"))

abiotic_elevation.df <- transect %>%
  rename(elevation = Elevation, site = Site, transect = Transect)

save(abiotic_elevation.df, 
     file = paste0(data_folder, "abiotic_elevation.RData"))

# Make a abiotic dataframe at the quadrat level
abiotic_quadrat.df <- quadrat %>%
  select(Site, Transect, Quadrat)  %>%
  left_join(transect2, 
            by = c("Site", "Transect")) %>%
  left_join(transect_hobo2,
            by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect"))  %>%
  left_join(quadrat_penetrometer2,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(quadrat_canopy_cover2,
            by = c("Site", "Transect", "Quadrat")) %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat)

save(abiotic_quadrat.df, 
     file = paste0(data_folder, "abiotic_quadrat.RData"))

```

```{r rq1_seedlingcover}
domseedlingcover_rq1.df <- specieslvl_dom_seedling_count2 %>%
  filter(`Dom Species ID` != 4) %>%
  left_join(specieslvl_dom_leaf_area3,
            by = c("Site", "Transect", "Quadrat", "Dom Species ID")) %>%
  left_join(quadrat_penetrometer2,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(quadrat_canopy_cover2,
            by = c("Site", "Transect", "Quadrat")) %>% 
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  left_join(transect_hobo2,
            by = c("Site", "Transect")) %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat, species_id = `Species ID`, dom_species_id = `Dom Species ID`) %>%
  left_join(leaf_traits2,
            by = c("species_id" = "Species ID")) %>%
  mutate(species_id = factor(species_id),
         dom_species_id = factor(species_id))

save(domseedlingcover_rq1.df, file = paste0(data_folder, "domseedlingcover_rq1.RData"))
```

```{r rq1_shannons}

domshannons_rq1.df <- quadrat_dom_seedling_count2 %>%
  left_join(quadrat_dom_leaf_area3,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(quadrat_penetrometer2,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(quadrat_canopy_cover2,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  left_join(transect_hobo2,
            by = c("Site", "Transect")) %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat)

save(domshannons_rq1.df, file = paste0(data_folder, "domshannons_rq1.RData"))
```

```{r rq1_sla}
domsla_rq1.df <- dom_leaf_area3 %>%
  left_join(species_id3,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(specieslvl_dom_seedling_count2,
            by = c("Site", "Transect", "Quadrat", "Dom Species ID", "Species ID"))%>%
  left_join(specieslvl_dom_leaf_area3 %>% select(-total_dom_leaf_dry_weight),
            by = c("Site", "Transect", "Quadrat", "Dom Species ID")) %>%
  # left_join(specieslvl_dom_seedling_count2,
  #           by = c("Site", "Transect", "Quadrat", "Dom Species ID")) %>%
  left_join(quadrat_penetrometer2,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(quadrat_canopy_cover2,
  by = c("Site", "Transect", "Quadrat")) %>% # Excluded since the data is extremely inbalanced
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  left_join(transect_hobo2,
            by = c("Site", "Transect")) %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat, species_id = `Species ID`, dom_species_id = `Dom Species ID`) 


# Mutate variables for modelling with
domsla_rq1.df %<>%
  mutate(dom_sla_weighted_abundance = dom_sla/dom_abundance)   %>%
  # left_join(leaf_traits2 %>% mutate(species_id = as.numeric(`Species ID`)) %>% select(-`Species ID`),
            # by = c("species_id")) %>%
  mutate(dom_seedling_cover = dom_seedling_cover/100,
         overall_seedling_cover = overall_seedling_cover/100,
         scaled_dom_seedling_cover = (dom_seedling_cover - mean(dom_seedling_cover))/sqrt(var(dom_seedling_cover)),
         scaled_overall_seedling_cover = (overall_seedling_cover - mean(overall_seedling_cover))/sqrt(var(overall_seedling_cover)),
         scaled_av_trans_elevation = (av_trans_elevation - mean(av_trans_elevation))/sqrt(var(av_trans_elevation))) %>%
  mutate(species_id = factor(species_id), 
         dom_species_id = factor(dom_species_id),
         transect = factor(transect), quadrat = factor(quadrat))  %>%
  select(-av_dom_leaf_dry_weight,-total_dom_leaf_dry_weight, -species_id, -leaf_area,
         -total_dom_leaf_area, -av_dom_sla_from_ind, -av_dom_sla_from_total,
         -species_richness) 


# domsla_rq1.df %<>%
#   mutate(av_quad_lai = ifelse(is.na(av_quad_lai), disturbed_mean_lai, av_quad_lai)) %>%
#   select(-av_quad_gft)

# Calculate Functional Richness, Functional Evenness and Functional Divergence
domsla_rq1.df %<>%
  group_by(site, transect, quadrat) %>%
  # select(dom_species_id, dom_sla) %>%
  mutate(sla_character_range = max(dom_sla) - min(dom_sla)) %>%
  group_by(site, transect, quadrat, dom_species_id) %>%
  mutate(sla_species_niche_space = max(dom_sla - min(dom_sla))) %>%
  ungroup() %>%
  mutate(sla_functional_richness = sla_species_niche_space/sla_character_range)


save(domsla_rq1.df, file = paste0(data_folder, "domsla_rq1.RData"))

# Create community aggregated SLA based on dom_seedling_cover
# Benefits: is a proportion of entire quadrat, so accounts for non-dominant species
# Disadvantages: is a subjective measure...
total_dom_abundance <- domsla_rq1.df %>%
  select(site, transect, quadrat, dom_species_id, dom_abundance) %>%
  distinct() %>%
    group_by(site, transect, quadrat) %>%
  mutate(total_dom_abundance = sum(dom_abundance)) %>%
    ungroup() %>%
  mutate(scaled_total_dom_abundance = (total_dom_abundance - mean(total_dom_abundance))/sqrt(var(total_dom_abundance)))%>%
  mutate(scaled_dom_abundance = (dom_abundance - mean(dom_abundance))/sqrt(var(dom_abundance))) %>%
  select(-dom_abundance)

cover_agg <- domsla_rq1.df %>%
  # select(site, transect, quadrat, dom_species_id, dom_sla, dom_seedling_cover) %>%
  group_by(site, transect, quadrat, dom_species_id) %>%
  mutate(sla_mean = mean(dom_sla), sla_sd = sqrt(var(dom_sla)))  %>%
  mutate(sla_cover = dom_sla*dom_seedling_cover,
         sla_cw_mean = mean(sla_cover),
         sla_cw_sd = sqrt(var(sla_cover))) %>%
  group_by(site, transect, quadrat) %>%
  mutate(sla_cover_total_sd = sqrt(var(sla_cover))) %>%
  ungroup()

cover_agg_sum <- cover_agg %>%
  select(site, transect, quadrat, dom_species_id, sla_cw_mean, sla_cover_total_sd) %>%
  distinct()  %>%
  group_by(site, transect, quadrat) %>%
  mutate(sla_ca_mean = sum(sla_cw_mean), sla_ca_sd = sla_cover_total_sd) %>%
  select(-sla_cw_mean, -sla_cover_total_sd, -dom_species_id) %>%
  ungroup() %>%
  distinct()


cover_agg2 <- cover_agg %>%
  left_join(cover_agg_sum,
            by = c("site", "transect", "quadrat")) %>%
  left_join(total_dom_abundance,
            by = c("site", "transect", "quadrat", "dom_species_id"))

# Choose which community aggregated to use: cover or abundance
community.df <- cover_agg2

communityagg_vars <- c("site", "transect", "quadrat", 
          "sla_ca_mean", "sla_ca_sd",
          "overall_seedling_cover", "scaled_overall_seedling_cover", 
          "total_dom_abundance", "scaled_total_dom_abundance",
          "av_trans_decomposition", "max_temp", "av_quad_compaction", "av_quad_lai", "av_quad_gft")

coefficient_variance_vars <- c("site", "transect", "quadrat", "dom_species_id",
                               "dom_sla", "sla_cover",
                               "sla_mean", "sla_sd", "sla_cw_mean", "sla_cw_sd",
                               "dom_seedling_cover", "overall_seedling_cover", "dom_abundance",
                               "scaled_dom_seedling_cover", "scaled_overall_seedling_cover", "scaled_dom_abundance",
                               "av_trans_decomposition", "max_temp", "av_quad_compaction", "av_quad_lai", "av_quad_gft")

ind_vars <- c("site", "transect", "quadrat", "dom_species_id",
             "sla_cover", "dom_sla",
             "dom_seedling_cover", "overall_seedling_cover", "dom_abundance",
             "scaled_dom_seedling_cover", "scaled_overall_seedling_cover", "scaled_dom_abundance",
             "av_trans_decomposition", "max_temp", "av_quad_compaction", "av_quad_lai", "av_quad_gft")

sla_ind.df <- community.df %>%
  select(one_of(ind_vars)) %>%
  distinct() %>%
  rename(sla_cw = sla_cover) %>%
  ungroup() %>%
  mutate(scaled_av_quad_lai = (av_quad_lai - mean(av_quad_lai))/sqrt(var(av_quad_lai)))%>%
  mutate(site_trans = factor(paste0(site, transect)))

sla_com.df <- community.df %>%
  select(one_of(communityagg_vars)) %>%
  distinct()%>%
  mutate(site_trans = factor(paste0(site, transect)))

sla_var.df <- community.df %>%
  select(one_of(coefficient_variance_vars)) %>%
  distinct()

save(sla_ind.df, file = paste0(data_folder, "sla_ind.RData"))
save(sla_com.df, file = paste0(data_folder, "sla_com.RData"))
save(sla_var.df, file = paste0(data_folder, "sla_var.RData"))
```

```{r rq2_hobo_timeseries}
hobo_nofilter2.df <- hobo_nofilter%>%
  left_join(max_min_hobo2, by=c("Site", "Transect", "hobo_id", 
                                "start_hobo", "end_hobo")) %>%
  mutate(hobo_id = factor(hobo_id))  %>%
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(transect_penetrometer2,
            by = c("Site", "Transect")) %>%
  left_join(transect_canopy_cover2,
  by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  rename(site = Site, transect= Transect)  %>%
  mutate(transect = factor(transect)) %>%
  arrange(desc(hobo_id), date_time)%>%
  mutate(time24 = as.numeric(substr(date_time, 12, 13)) + 
                         as.numeric(substr(date_time, 15, 16))/60)


hobo_rq2.df <- hobo3 %>%
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(transect_penetrometer2,
            by = c("Site", "Transect")) %>%
  left_join(transect_canopy_cover2,
  by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  rename(site = Site, transect= Transect)  %>%
  mutate(transect = factor(transect)) %>%
  arrange(desc(hobo_id), date_time) %>%
  # filter(hobo_id %in% c("3", "8", "13", "6")) %>%
  filter(date_time > as.POSIXct(strftime("2017-09-26 3:00:00", 
                                         "%Y-%m-%d %H:%M:%S")),
         date_time < as.POSIXct(strftime("2017-09-28 22:00:00", 
                                         "%Y-%m-%d %H:%M:%S"))) %>%
  select(site, transect, hobo_id, date_time, temp, rel_humid, av_trans_elevation, av_trans_compaction, av_trans_lai, av_trans_gft, av_trans_decomposition) %>%
  mutate(time24 = as.numeric(substr(date_time, 12, 13)) + 
                         as.numeric(substr(date_time, 15, 16))/60)

  
save(hobo_rq2.df, file = paste0(data_folder, "hobo_rq2.RData"))
save(hobo_nofilter2.df, file = paste0(data_folder, "hobo_nofilter2.RData"))
```

```{r rq3_species_richness}
# Spread each variable to a quadrat level
abundance_spread <- specieslvl_dom_seedling_count2 %>%
  mutate(abundance_sample = paste0("dom_", `Dom Species ID`, "_abundance")) %>%
  select(Site, Transect, Quadrat, abundance_sample, dom_abundance) %>%
  spread(abundance_sample, dom_abundance)

seedlingcover_spread <- specieslvl_dom_seedling_count2 %>%
  mutate(seedlingcover_sample = paste0("dom_", `Dom Species ID`, "_seedling_cover")) %>%
  select(Site, Transect, Quadrat, seedlingcover_sample, dom_seedling_cover) %>%
  spread(seedlingcover_sample, dom_seedling_cover)

overall_seedling_cover_spread <-specieslvl_dom_seedling_count2%>%
  select(Site, Transect, Quadrat, overall_seedling_cover) %>%
  mutate(overall_seedling_cover = overall_seedling_cover/100) %>%
  distinct()


sla_spread <- specieslvl_dom_leaf_area3 %>%
  mutate(sla_sample = paste0("dom_", `Dom Species ID`, "_sla")) %>%
  select(Site, Transect, Quadrat, sla_sample, av_dom_sla_from_ind) %>%
  spread(sla_sample, av_dom_sla_from_ind)

species_richness_rq3.df <- species_id3 %>%
  left_join(abundance_spread,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(seedlingcover_spread,
            by = c("Site", "Transect", "Quadrat"))  %>%
  left_join(overall_seedling_cover_spread,
            by = c("Site", "Transect", "Quadrat"))%>%
  left_join(sla_spread,
            by = c("Site", "Transect", "Quadrat"))%>%
  left_join(quadrat_penetrometer2,
            by = c("Site", "Transect", "Quadrat")) %>%
  # left_join(quadrat_canopy_cover2,
            # by = c("Site", "Transect", "Quadrat")) %>% # Excluded since the data is extremely inbalanced
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  left_join(transect_hobo2,
            by = c("Site", "Transect")) %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat) %>%
  ungroup() %>%
  mutate(transect = factor(transect), quadrat = factor(quadrat))

save(species_richness_rq3.df, file = paste0(data_folder, "species_richness_rq3.RData"))
```


```{r domseedlingcover_alicia}
# Alicia's seedling cover dataset: Probably for ricky as well...
abundance_spread <- specieslvl_dom_seedling_count2 %>%
  filter(`Dom Species ID` != 4) %>%
  mutate(abundance_sample = paste0("dom_", `Dom Species ID`, "_abundance")) %>%
  select(Site, Transect, Quadrat, abundance_sample, dom_abundance) %>%
  spread(abundance_sample, dom_abundance)

seedlingcover_spread <- specieslvl_dom_seedling_count2 %>%
  mutate(seedlingcover_sample = paste0("dom_", `Dom Species ID`, "_seedling_cover")) %>%
  select(Site, Transect, Quadrat, seedlingcover_sample, dom_seedling_cover) %>%
  mutate(dom_seedling_cover = dom_seedling_cover/100) %>%
  spread(seedlingcover_sample, dom_seedling_cover)

overall_seedling_cover_spread <-specieslvl_dom_seedling_count2%>%
  select(Site, Transect, Quadrat, overall_seedling_cover) %>%
  mutate(overall_seedling_cover = overall_seedling_cover/100) %>%
  distinct()

sla_spread <- specieslvl_dom_leaf_area3 %>%
  mutate(sla_sample = paste0("dom_", `Dom Species ID`, "_sla")) %>%
  select(Site, Transect, Quadrat, sla_sample, av_dom_sla_from_ind) %>%
  spread(sla_sample, av_dom_sla_from_ind)

domseedlingcover_spread.df <- overall_seedling_cover_spread %>%
  left_join(abundance_spread,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(seedlingcover_spread,
            by = c("Site", "Transect", "Quadrat"))  %>%
  left_join(sla_spread,
            by = c("Site", "Transect", "Quadrat"))%>%
  left_join(quadrat_penetrometer2,
            by = c("Site", "Transect", "Quadrat")) %>%
  left_join(transect2,
            by = c("Site", "Transect")) %>%
  left_join(transect_filter_paper2,
            by = c("Site", "Transect")) %>%
  left_join(transect_hobo2,
            by = c("Site", "Transect")) %>%
  rename(site = Site, transect = Transect, quadrat = Quadrat) %>%
  ungroup() %>%
  mutate(transect = factor(transect), quadrat = factor(quadrat))

save(domseedlingcover_spread.df, file = paste0(data_folder, "domseedlingcover_spread.RData"))
```

