---
title: "model_development"
output: html_document
---

```{r}
# Load the datasets
load(paste0(data_folder, "abiotic_quadrat.RData"))
load(paste0(data_folder, "abiotic_filterpaper.RData"))
load(paste0(data_folder, "abiotic_canopycover.RData"))
load(paste0(data_folder, "abiotic_penetrometer.RData"))
load(paste0(data_folder, "hobo_rq2.RData"))

```

```{r}
# Create 6 hour intervals for time series graphs
start <- as.POSIXct(strptime("2017-09-25 04:00:00", "%Y-%m-%d %H:%M:%S"))
interval <- 60*6
end <- start + as.difftime(4, units="days")
labels = seq(from=start, by=interval*60, to=end)

# Create just the time intervals instead, since shading is used for days
start2 <- as.POSIXct(strptime("2017-09-25 18:00:00", "%Y-%m-%d %H:%M:%S"))
end2 <- start + as.difftime(5, units="days")
labels2 = seq(from=start2, by=interval*60, to=end2)
time_labels = format(labels2, format = "%H:%M:%S")

labels = labels[2:17]
time_labels <- substr(time_labels[2:17], 1, 5)

# Filter the data between useable dates
datarq2 <- hobo_rq2.df # Ten Hour Lag..


# Get shading for different days
hobo_days <- data.frame(startday = c(as.POSIXct(strftime("2017-09-26 3:00:01", "%Y-%m-%d %H:%M:%S")),
                                     as.POSIXct(strftime("2017-09-26 00:00:00", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-27 00:00:00", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-28 00:00:00", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins")),
                        endday =   c(as.POSIXct(strftime("2017-09-25 23:59:59", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-26 23:59:59", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-27 23:59:59", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-28 22:00:00", "%Y-%m-%d %H:%M:%S")))) %>%
                        mutate(day = c("Monday", "Tuesday", "Wednesday", "Thursday"),
                               day = factor(day,
                                            levels = c("Monday", "Tuesday", "Wednesday", "Thursday"),
                                            ordered = TRUE)) %>% 
  tbl_df()

# Show filter point for late hobos
min_new_time <- as.POSIXct(strftime("2017-09-28 03:00:00", "%Y-%m-%d %H:%M:%S"))

latehobos <- data.frame(ytemp = c(25.5, 28),
                        xdatetime = c(min_new_time, min_new_time)) %>%
  tbl_df
```

### Site
```{r}
# Plot the graphs
ggplot() +
  theme_project() +
  scale_x_datetime(breaks = labels
                   ,labels = time_labels
                   ) +
  theme(axis.text.x = element_text(angle = 45, 
                                   vjust = 1,
                                   hjust = 1)) +
  geom_rect(aes(xmin=startday, xmax=endday, ymin = 25.5, ymax = 28, fill = day),
            data = hobo_days, alpha = 0.4)   +
  scale_fill_tableau(name = "Day")+
  # geom_line(aes(x=date_time, y=temp, col=hobo_id),
             # data = datarq2, size=1) +
  # scale_colour_pander(name = "Hobo ID")+
  geom_point(aes(x=date_time, y=temp, col=site),
             data = datarq2, size=1) +
  scale_colour_manual(name = "Site",
                      values = colours.site) +
  ggtitle("Temperature over Time") +
  xlab("Time of Day") +
  ylab("Temperature (Degrees Celsius)") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green)) +
  geom_line(aes(x=xdatetime, y=ytemp),
            data = latehobos)

ggsave(paste0(data_folder, "temp_timeseries.png"), width = 6, height = 3.5, dpi = 900)
```

### Univariate Relationship
```{r}

  
  

# Decopmosition
ggplot() + 
  geom_point(aes(x=site, y=decomposition, col = site),
       data = abiotic_filterpaper.df) +
  geom_boxplot(aes(x=site, y=decomposition, col = site),
       data = abiotic_filterpaper.df)+
  ggtitle("Decomposition") +
  xlab("Site") +
  ylab("Decomposition Rate (grams/days)") +
  theme_project() +
  scale_colour_manual(values = colours.site) +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green)) +
  geom_abline(slope = 0, intercept = 0)

# LAI
ggplot(aes(x=site, y=lai, col = site),
       data = abiotic_canopycover.df) + 
  geom_point() +
  geom_boxplot() +
  ggtitle("Leaf Area Index") +
  theme_project()+
  scale_colour_manual(values = colours.site) +
  xlab("Site") +
  ylab("Leaf Area Index") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green))


# Compaction
ggplot(aes(x=site, y=compaction, col = site),
       data = abiotic_penetrometer.df) + 
  geom_boxplot() +
  ggtitle("Penetrometer") +
  theme_project()+
  scale_colour_manual(values = colours.site) +
  xlab("Site") +
  ylab("Compaction (pressure)") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green))

```

# Bivariate Relationships
```{r}
## Abiotic variables
abiotic_vars <- c("av_quad_compaction", "av_trans_decomposition", "min_temp", "max_temp", "range_temp", "av_quad_lai", "av_quad_gft")


abiotic_quadrat.df %>% 
  select(one_of(abiotic_vars)) %>%
  cor() %>%
  round(digits=2)

abiotic_vars2 <- c("av_quad_compaction", "av_trans_decomposition", "max_temp", "av_quad_lai")

abiotic_quadrat.df %>% 
  select(one_of(abiotic_vars2)) %>%
  cor() %>%
  round(digits=2)

# correlation results
# elevation will account for decopmosition and min_temperature, however we will leave compaction in the model for now as it is at the quadrat level and may provide additional information
# range_temp will account for max_temp
# so model elevation, range_temp, compaction, lai

abiotic_quadrat.df %>%
  ggplot(aes(x=av_trans_elevation, y=av_quad_compaction)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)+
  theme_project()+
  scale_colour_tableau() +
  xlab("Elevation (m)") +
  ylab("Compaction (pressure)") +
  ggtitle("Compaction vs Elevation")

abiotic_quadrat.df %>%
  ggplot(aes(x=av_trans_elevation, y=av_trans_decomposition)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)+
  theme_project()+
  scale_colour_tableau() +
  xlab("Elevation (m)") +
  ylab("Decomposition") +
  ggtitle("Compaction vs Decomposition")

abiotic_quadrat.df %>%
  mutate(av_quad_lai = ifelse(av_quad_lai == disturbed_mean_lai, NA, av_quad_lai)) %>%
  ggplot(aes(x=av_trans_elevation, y=av_quad_lai)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)+
  theme_project()+
  scale_colour_tableau() +
  xlab("Elevation (m)") +
  ylab("Leaf Area Index") +
  ggtitle("Elevation vs LAI (NA's)")

abiotic_quadrat.df %>%
  # mutate(av_quad_lai = ifelse(av_quad_lai == disturbed_mean_lai, NA, av_quad_lai)) %>%
  ggplot(aes(x=av_trans_elevation, y=av_quad_lai)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)+
  theme_project()+
  scale_colour_tableau() +
  xlab("Elevation (m)") +
  ylab("Leaf Area Index") +
  ggtitle("Elevation vs LAI (Imputed)")

abiotic_quadrat.df %>%
  # mutate(av_quad_lai = ifelse(av_quad_lai == disturbed_mean_lai, NA, av_quad_lai)) %>%
  ggplot(aes(x=max_temp, y=av_quad_lai)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)+
  theme_project()+
  scale_colour_tableau() +
  xlab("Max Temperature") +
  ylab("Leaf Area Index") +
  ggtitle("Max Temperature vs LAI (Imputed)")
```


### Temperature Spline Fit
```{r}
# Filter the data between useable dates
datarq2 <- hobo_rq2.df # Ten Hour Lag..

datarq2 %<>%
  mutate(time24 = as.numeric(substr(date_time, 12, 13)) + 
                         as.numeric(substr(date_time, 15, 16))/60)

# Plot the graphs
ggplot() +
  theme_project() +
  scale_fill_tableau(name = "Day")+
  geom_point(aes(x=time24, y=temp, col=site),
             data = datarq2, size=1) +
  scale_colour_manual(name = "Site",
                      values = colours.site) +
  ggtitle("Temperature over 24 Period") +
  xlab("Hour") +
  scale_x_continuous(breaks = seq(0, 24, 6)) +
  ylab("Temperature (Degrees Celsius)") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green))


```

```{r}
k1 <- 14
k2 <- 14
k3 <- 17

splinefit <- lm(temp ~ site + bs(time24, knots = c(k1, k2, k3)) + site:bs(time24, knots = c(k1, k2, k3)),
          data = datarq2)


# inla_spline <- inla(temp ~ site + bs(time24, knots = c(k1, k2, k3)) + site:bs(time24, knots = c(k1, k2, k3)),
#                     family = "gaussian",
#                     data = datarq2)

summary(splinefit)

```

```{r}

# Add the spline line onto the scatterplot
pred_p <- data.frame(time24 = seq(0, 24, 0.5), site = "P", metric = " Spline - Pristine", av_trans_elevation = 60)
pred_d <- data.frame(time24 = seq(0, 24, 0.5), site = "D", metric = " Spline - Disturbed", av_trans_elevation = 60)

pred_p %<>% mutate(pred_temp = predict(splinefit, pred_p))
pred_d %<>% mutate(pred_temp = predict(splinefit, pred_d))

pred_fits <- rbind(pred_p, pred_d)



 
ggplot() +
  geom_point(aes(x=time24, y=temp, col = site),
             size = 0.2,
             data = datarq2) +
  geom_line(aes(x = time24, y = pred_temp, col = metric),
            size = 1.2,
            data =  pred_fits) +
  theme_project() +
  scale_colour_manual(values = colours.splinefit,
                      name = "Metric") +
  scale_x_continuous(breaks = seq(0, 24, 3)) +
  ylab("Temperature") +
  xlab("24 Hour Time") +
  ggtitle("Temperature vs Time")


```

### Model Fit

```{r}

pred <- splinefit$fitted.values

datarq2 %<>%
  mutate(temp_pred = pred,
         residuals = temp - temp_pred,
         stdresiduals = (residuals-mean(residuals))/sqrt(var(residuals))) 

datarq2 %>%
  ggplot(aes(x=temp, y=temp_pred, col=site)) +
  geom_point() +
  theme_project() +
  geom_abline(slope=1, intercept=0)+
  coord_equal() +
  scale_colour_manual(values = colours.site)

datarq2 %>%
  ggplot(aes(x=temp_pred, y=stdresiduals, col=site)) +
  geom_point() +
  theme_project()+
  scale_colour_manual(values = colours.site)

```
