---
title: "model_development"
output: html_document
---

#### Linear Spline Model 
```{r}
datarq2 %<>% mutate(lagtemp = lag(temp)) %>% filter(!is.na(lagtemp))

k1 <- 14
k2 <- 14
k3 <- 17

splinefit <- lm(temp ~ site + lagtemp, # + bs(time24, knots = c(k1, k2, k3)) + site:bs(time24, knots = c(k1, k2, k3)),
          data = datarq2)


# inla_spline <- inla(temp ~ site + bs(time24, knots = c(k1, k2, k3)) + site:bs(time24, knots = c(k1, k2, k3)),
#                     family = "gaussian",
#                     data = datarq2)

summary(splinefit)


# acf(splinefit)
```

<!-- ```{r} -->

<!-- # Add the spline line onto the scatterplot -->
<!-- pred_p <- data.frame(time24 = seq(0, 24, 0.5), site = "P", metric = " Spline - Pristine", av_trans_elevation = 60) -->
<!-- pred_d <- data.frame(time24 = seq(0, 24, 0.5), site = "D", metric = " Spline - Disturbed", av_trans_elevation = 60) -->

<!-- pred_p %<>% mutate(pred_temp = predict(splinefit, pred_p)) -->
<!-- pred_d %<>% mutate(pred_temp = predict(splinefit, pred_d)) -->

<!-- pred_fits <- rbind(pred_p, pred_d) -->

<!-- datarq2 %<>% -->
<!--   mutate(pred_temp = predict(splinefit, datarq2)) -->

<!-- ggplot() + -->
<!--   geom_point(aes(x=time24, y=temp, col = site), -->
<!--              size = 0.2, -->
<!--              data = datarq2) + -->
<!--   geom_line(aes(x = time24, y = pred_temp, col = site), -->
<!--             size = 1.2, -->
<!--             data =  datarq2) + -->
<!--   theme_project() + -->
<!--   scale_colour_manual(values = colours.splinefit, -->
<!--                       name = "Metric") + -->
<!--   scale_x_continuous(breaks = seq(0, 24, 3)) + -->
<!--   ylab("Temperature") + -->
<!--   xlab("24 Hour Time") + -->
<!--   ggtitle("Temperature vs Time") -->


<!-- ``` -->

### Model Fit
_Residuals_
```{r}
pred <- splinefit$fitted.values

datarq2 %<>%
  mutate(temp_pred = pred,
         residuals = temp - temp_pred,
         stdresiduals = (residuals-mean(residuals))/sqrt(var(residuals))) 

datarq2 %>%
  ggplot(aes(x=temp, y=temp_pred, col=site)) +
  geom_point() +
  theme_project() +
  geom_abline(slope=1, intercept=0)+
  coord_equal() +
  scale_colour_manual(values = colours.site)

datarq2 %>%
  ggplot(aes(x=temp_pred, y=stdresiduals, col=site)) +
  geom_point() +
  theme_project()+
  scale_colour_manual(values = colours.site)

```

_Autocorrelation_
```{r}

acf(splinefit)

# Regress the one step lag residuals against forward residuals
res <- datarq2$residuals

y <- res[-length(res)]
x <- res[-1]

fit_ac <- lm(y ~ x)
summary(fit_ac)


```





