---
title: "model_development"
output: html_document
---

```{r}
# Use the choose files function to get the location of the datasets on your computer
# choose.files()

# Should get an output like:
# "C:\\Users\\Jacob\Project\\Data\\biotic_leaftraits.RData"

# Copy the folder spot below, and copy the """".RData file into the load function below

location <- "C:\\Users\\Jacob\\Dropbox\\Semester 2 2017\\MXB344\\Project\\Data\\"

# Load the datasets
load(paste0(location, "abiotic_quadrat.RData"))
load(paste0(location, "abiotic_filterpaper.RData"))
load(paste0(location, "abiotic_canopycover.RData"))
load(paste0(location, "abiotic_penetrometer.RData"))
load(paste0(location, "hobo_rq2.RData"))

bg_green <- rgb(223, 241, 204, maxColorValue = 255)
```

## Research Question 2: Abiotic Indicators
### Univariate Relationships
```{r}
# Create 6 hour intervals for time series graphs
start <- as.POSIXct(strptime("2017-09-25 04:00:00", "%Y-%m-%d %H:%M:%S"))
interval <- 60*6
end <- start + as.difftime(4, units="days")
labels = seq(from=start, by=interval*60, to=end)

# Create just the time intervals instead, since shading is used for days
start2 <- as.POSIXct(strptime("2017-09-25 18:00:00", "%Y-%m-%d %H:%M:%S"))
end2 <- start + as.difftime(5, units="days")
labels2 = seq(from=start2, by=interval*60, to=end2)
time_labels = format(labels2, format = "%H:%M:%S")

labels = labels[2:17]
time_labels <- substr(time_labels[2:17], 1, 5)

# Filter the data between useable dates
datarq2 <- hobo_rq2.df # Ten Hour Lag..


# Get shading for different days
hobo_days <- data.frame(startday = c(as.POSIXct(strftime("2017-09-26 3:00:01", "%Y-%m-%d %H:%M:%S")),
                                     as.POSIXct(strftime("2017-09-26 00:00:00", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-27 00:00:00", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-28 00:00:00", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins")),
                        endday =   c(as.POSIXct(strftime("2017-09-25 23:59:59", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-26 23:59:59", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-27 23:59:59", "%Y-%m-%d %H:%M:%S"))+as.difftime(60*10, units="mins"),
                                     as.POSIXct(strftime("2017-09-28 22:00:00", "%Y-%m-%d %H:%M:%S")))) %>%
                        mutate(day = c("Monday", "Tuesday", "Wednesday", "Thursday"),
                               day = factor(day,
                                            levels = c("Monday", "Tuesday", "Wednesday", "Thursday"),
                                            ordered = TRUE)) %>% 
  tbl_df()

# Show filter point for late hobos
min_new_time <- as.POSIXct(strftime("2017-09-28 03:00:00", "%Y-%m-%d %H:%M:%S"))

latehobos <- data.frame(ytemp = c(25.5, 28),
                        xdatetime = c(min_new_time, min_new_time)) %>%
  tbl_df


# Plot the graphs
ggplot() +
  theme_project() +
  scale_x_datetime(breaks = labels
                   ,labels = time_labels
                   # limits = c(as.POSIXct(strptime("2017-09-25 18:00:00",
                   # "%Y-%m-%d %H:%M:%S")) + as.difftime(10, units="hours"),
                              # as.POSIXct(strptime("2017-09-28 12:00:00",
                   # "%Y-%m-%d %H:%M:%S")) + as.difftime(10, units="hours"))
                   ) +
  theme(axis.text.x = element_text(angle = 45, 
                                   vjust = 1,
                                   hjust = 1)) +
  geom_rect(aes(xmin=startday, xmax=endday, ymin = 25.5, ymax = 28, fill = day),
            data = hobo_days, alpha = 0.4)   +
  scale_fill_tableau(name = "Day")+
  # geom_line(aes(x=date_time, y=temp, col=hobo_id),
             # data = datarq2, size=1) +
  # scale_colour_pander(name = "Hobo ID")+
  geom_line(aes(x=date_time, y=temp, col=site),
             data = datarq2, size=1) +
  scale_colour_manual(name = "Site",
                      values = colours.site) +
  ggtitle("Temperature over Time") +
  xlab("Time of Day") +
  ylab("Temperature (Degrees Celsius)") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green)) +
  geom_line(aes(x=xdatetime, y=ytemp),
            data = latehobos)

ggplot() +
  theme_project() +
  scale_x_datetime(breaks = labels
                   ,labels = time_labels
                   # limits = c(as.POSIXct(strptime("2017-09-25 18:00:00",
                   # "%Y-%m-%d %H:%M:%S")) + as.difftime(10, units="hours"),
                              # as.POSIXct(strptime("2017-09-28 12:00:00",
                   # "%Y-%m-%d %H:%M:%S")) + as.difftime(10, units="hours"))
                   ) +
  theme(axis.text.x = element_text(angle = 45, 
                                   vjust = 1,
                                   hjust = 1)) +
  geom_rect(aes(xmin=startday, xmax=endday, ymin = 25.5, ymax = 28, fill = day),
            data = hobo_days, alpha = 0.4)   +
  scale_fill_tableau(name = "Day")+
  # geom_line(aes(x=date_time, y=temp, col=hobo_id),
             # data = datarq2, size=1) +
  # scale_colour_pander(name = "Hobo ID")+
  geom_line(aes(x=date_time, y=temp, col=paste0(site, ":", transect)),
             data = datarq2, size=1) +
  scale_color_pander(name = "Transect") +
                      # values = colours.site) +
  ggtitle("Temperature over Time (D1, D2, P1, P3)") +
  xlab("Time of Day") +
  ylab("Temperature (Degrees Celsius)") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green))

```

### Univariate Relationship
```{r}
abiotic_elevation.df %>%
  select(elevation, site, transect) %>%
  distinct() %>%
  ggplot(aes(x=paste0(site, ":", transect), y=elevation, col = site)) +
  geom_point(size=2.27) +
  geom_boxplot() +
  xlab("Site") +
  ylab("Elevation (m)") +
  theme_project() +
  scale_colour_manual(values = colours.site) +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green)) +
  ggtitle("Elevation vs Sites and Transects")
  
  

# Decopmosition
ggplot(aes(x=site, y=decomposition, col = site),
       data = abiotic_filterpaper.df) + 
  geom_boxplot() +
  ggtitle("Decomposition") +
  xlab("Site") +
  ylab("Decomposition Rate (grams/days)") +
  theme_project() +
  scale_colour_manual(values = colours.site) +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green))

# LAI
ggplot(aes(x=site, y=lai, col = site),
       data = abiotic_canopycover.df) + 
  geom_boxplot() +
  ggtitle("Leaf Area Index") +
  theme_project()+
  scale_colour_manual(values = colours.site) +
  xlab("Site") +
  ylab("Leaf Area Index") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green))


# Compaction
ggplot(aes(x=site, y=compaction, col = site),
       data = abiotic_penetrometer.df) + 
  geom_boxplot() +
  ggtitle("Penetrometer") +
  theme_project()+
  scale_colour_manual(values = colours.site) +
  xlab("Site") +
  ylab("Compaction (pressure)") +
  theme(legend.background = element_rect(bg_green),
        legend.box.background = element_rect(fill=bg_green, color=bg_green),
        legend.key = element_rect(fill=bg_green),
        plot.background = element_rect(bg_green, color=bg_green))

```

# Bivariate Relationships
```{r}
abiotic_quadrat.df




```


