---
title: "model_development"
output: html_document
---

#### Correlation
```{r}
sladata <- sla_com.df

# biotic_vars <- c("dom_seedling_cover", "overall_seedling_cover", "dom_species_id")
# 
# sladata %>%
#   select(one_of(biotic_vars)) %>%
#   pairs(lower.panel = NULL)
# 
# sladata %>%
#   mutate(dom_species_id = as.numeric(dom_species_id)) %>%
#   select(one_of(biotic_vars)) %>%
#   cor()

# correlation results
# overall seedling cover is not needed. 
```


```{r}
# define the vector of possible predictors, exclude random effects
response <- "sla_ca_mean"
temp_predictors <- names(sladata)[-(which(names(sladata) %in% c("sla_ca_mean", "site", "transect", "quadrat",
                                                         "min_temp", "range_temp",
                                                         "overall_seedling_cover", "scaled_overall_seedling_cover",
                                                         "total_dom_abundance", "scaled_total_dom_abundance")))]

# Remove all leaf data
# interactions <- c("site:dom_species_id", "site:av_quad_gft", "site:av_quad_compaction",
#          "dom_species_id:scaled_av_trans_elevation", "dom_species_id:av_quad_gft", "dom_species_id:av_quad_compaction")

predictors <- c(temp_predictors, paste0(temp_predictors, " + ", temp_predictors, ":site"))
# predictors <- c(temp_predictors, interactions)

# Iterate through code that creates all possible combinations of predictors: 7 predictors means 7^2 combinations
possible_predictor_combinations <- list()
index <- 1

for (i in 1:length(predictors)) {
  for (j in i:length(predictors)) {
  possible_predictor_combinations[[index]] <- i:j
  index <- index + 1
  }
}

# Create formula's
formula_string_combinations <- list()

for (i in 1:length(possible_predictor_combinations)) {

  formula_string_combinations[[i]] <- predictors[possible_predictor_combinations[[i]][1]]

  if (length(possible_predictor_combinations[[i]]) > 1) {
    for (j in 2:length(possible_predictor_combinations[[i]])) {
      formula_string_combinations[[i]] <- paste(formula_string_combinations[[i]],
                                                predictors[possible_predictor_combinations[[i]][j]],
                                                sep = " + ")
    }
  }

}

# Find the full formula of predictors for INLA step
length_formulastring <- data.frame(Index=NA, Length=NA)

for (i in 1:length(formula_string_combinations)) {
  length_formulastring[i,1] <- i
  length_formulastring[i,2] <- nchar(formula_string_combinations[[i]])
}

full_formula <- length_formulastring %>% 
  arrange(desc(Length)) %>%
  head(1) %>%
  select(Length) %>%
  unlist(use.names = FALSE)
```




<!-- #### Ruwans Stepwise for Aggregate -->
<!-- ```{r} -->
<!-- # Run all possible INLA models -->
<!-- loglinear_stepwise_summary <- data.frame(Formula = "-", Log_Likelihood = NA) -->

<!-- # In for loop, run the model and combine the log likelihood estimate into a data.frame -->
<!-- for (i in 1:length(formula_string_combinations)) { -->
<!-- inla_formula <- as.formula(paste0("log(sla_ca_mean) ~ site + ", -->
<!--                           formula_string_combinations[[i]], -->
<!--                           " + f(transect, model='iid') + f(quadrat:transect, model = 'iid')")) -->

<!-- fit <- inla(inla_formula, -->
<!--             family = "gaussian", -->
<!--             data = sladata) -->

<!-- loglinear_stepwise_summary <- loglinear_stepwise_summary %>% -->
<!--   rbind(data.frame(Formula = formula_string_combinations[[i]], -->
<!--                    Log_Likelihood = summary(fit)[["mlik"]][2])) -->
<!-- print(i) -->
<!-- } -->

<!-- save(loglinear_stepwise_summary, file = paste0(data_folder, "loglinear_stepwise_summary.RData")) -->

<!-- # load(paste0(dropbox, "loglinear_stepwise_summary.RData")) -->
<!-- #  -->
<!-- # top10 <- loglinear_stepwise_summary %>% -->
<!-- #   arrange(desc(Log_Likelihood)) %>% -->
<!-- #   head(10) -->
<!-- #  -->
<!-- # top10 -->
<!-- ``` -->

<!-- ```{r} -->

<!-- load(paste0(data_folder, "loglinear_stepwise_summary.RData")) -->

<!-- loglinear_stepwise_summary %>% -->
<!--   arrange(desc(Log_Likelihood)) %>% -->
<!--   head(10) -->
<!-- # fit <-  -->

<!-- ``` -->

#### Final Model: Minimum Marginal log-Likelihood
```{r}
# RUn a model on the top 3 variables identified
inla_formula <- as.formula("log(sla_ca_mean) ~  site + f(transect, model='iid') + f(quadrat:transect, model = 'iid')")

fit <- inla(inla_formula,
            family = "gaussian",
            data = sladata,
            control.compute = list(cpo=TRUE),
            control.inla = list(strategy = "laplace"))

# analyse the output of the model
summary(fit)
```


#### Model Fit
```{r}
# summary(fit)
predictions <- fit$summary.fitted.values$mean
dataset <- sladata

pred.df <- dataset %>% 
      mutate(fitted = predictions,
             observed = log(sla_ca_mean),
             residuals = observed - fitted,
             std_residuals = (residuals - mean(residuals))/sqrt(var(residuals)),
             cpo = fit$cpo$pit)

## Fitted vs Predicted
pred.df %>%
  ggplot(aes(x = observed, y = fitted)) +
  geom_point() +
  xlab("Observed Mean SLA (CA)") +
  ylab("Fitted Values") +
  theme_project() +
  coord_equal() +
  geom_abline() +
  ggtitle("Observed vs Fitted SLA")

## Fitted vs Standardised Residuals
pred.df %>%
  ggplot(aes(x = fitted, y = std_residuals)) +
  geom_point() +
  xlab("Fitted Values") +
  ylab("Standardised Residuals") +
  theme_project() +
  geom_abline(slope = 0)+
  geom_abline(slope = 0, intercept = 1.5)+
  geom_abline(slope = 0, intercept = -1.5)

# Residuals QQ plot
qqnorm(pred.df$residuals)
qqline(pred.df$residuals)
title("Residuals                                                 ")

 # Histogram of predictions
pred.df %>%
  ggplot(aes(x = fitted)) +
  geom_histogram(bins=7) +
  theme_project() +
  ggtitle("Histograms of Fitted Values")
  

# CPO Values: QQ plot and Histogram
pred.df %>%
  ggplot(aes(x = cpo)) +
  geom_histogram(bins=7) +
  theme_project() +
  ggtitle("Histograms of CPO")

qqnorm(fit$cpo$pit)
qqline(fit$cpo$pit)
title("CPO                                       ")

```

#### Fixed Effect Credible Intervals
```{r }
## How to look at predictions and compare to original???
fixed <- summary(fit)$fixed
vec <- fixed[1:length(fixed)]
# random <- summary(fit)$random
n <- length(summary(fit)$fixed)
n1 <- n/7

# Collect and plot the intercals
# How to standardise the intervals?
# Standardise the response variable?
fixed.df <- data.frame(Estimate = row.names(fixed),
           Mean = vec[1:n1],
           SD = vec[(n1+1):(2*n1)],
           quant0.025 = vec[(2*n1+1):(3*n1)],
           quant0.5 = vec[(3*n1+1):(4*n1)],
           quant0.975 = vec[(4*n1+1):(5*n1)],
           mode = vec[(5*n1+1):(6*n1)]) %>%
  mutate(Estimate = factor(Estimate, levels = row.names(fixed)[n1:1], ordered = TRUE)) %>%
  tbl_df() %>%
  mutate(beta = 0:(n1-1)) %>%
  mutate(Est2 = paste0(Estimate, " - b", beta),
         Est2 = reorder(Est2, rev(beta)))

fixed.df %>%
  ggplot(aes(y = Est2, x = exp(quant0.5), xmin = exp(quant0.025), xmax = exp(quant0.975))) +
  geom_errorbarh() +
  theme_project() +
  ggtitle("SLA Agg - Fixed") +
  xlab("Credible Intervals") +
  ylab("Parameter") +
  geom_vline(xintercept = 0) +
  scale_x_continuous(breaks = seq(0, 40, 5))


ggsave(paste0(data_folder, "sla_", "agg","_estimates.png"), width = 3, height = 1.5, dpi = 900)
```


#### Real Fixed Effect Credible Intervals
```{r}
mean_fixedeffect.df <- data.frame(Parameter = c("Intercept","Scaled_Elevation", "Scaled_Cover")) %>%
  mutate(ID1_D = round(c(sum(fixed.df$quant0.5[c(1)]),
                   sum(fixed.df$quant0.5[c(2)]),
                   sum(fixed.df$quant0.5[c(5)])), digits=1)) %>%
  mutate(ID2_D = round(c(sum(fixed.df$quant0.5[c(1, 3)]),
                   sum(fixed.df$quant0.5[c(2, 7)]),
                   sum(fixed.df$quant0.5[c(5)])), digits=1)) %>%
  mutate(ID3_D = round(c(sum(fixed.df$quant0.5[c(1, 4)]),
                   sum(fixed.df$quant0.5[c(2, 8)]),
                   sum(fixed.df$quant0.5[c(5)])), digits=1)) %>%
  mutate(ID1_P = round(c(sum(fixed.df$quant0.5[c(1, 6)]),
                   sum(fixed.df$quant0.5[c(2)]),
                   sum(fixed.df$quant0.5[c(5)])), digits=1)) %>%
  mutate(ID2_P = round(c(sum(fixed.df$quant0.5[c(1, 3, 6)]),
                   sum(fixed.df$quant0.5[c(2, 7)]),
                   sum(fixed.df$quant0.5[c(5)])), digits=1)) %>%
  mutate(ID3_P = round(c(sum(fixed.df$quant0.5[c(1, 4, 6)]),
                   sum(fixed.df$quant0.5[c(2, 8)]),
                   sum(fixed.df$quant0.5[c(5)])), digits=1)) %>%
  gather(Scenario, Median, -Parameter)

lb_fixedeffect.df <- data.frame(Parameter = c("Intercept","Scaled_Elevation", "Scaled_Cover")) %>%
  mutate(ID1_D = round(c(sum(fixed.df$quant0.025[c(1)]),
                   sum(fixed.df$quant0.025[c(2)]),
                   sum(fixed.df$quant0.025[c(5)])), digits=1)) %>%
  mutate(ID2_D = round(c(sum(fixed.df$quant0.025[c(1, 3)]),
                   sum(fixed.df$quant0.025[c(2, 7)]),
                   sum(fixed.df$quant0.025[c(5)])), digits=1)) %>%
  mutate(ID3_D = round(c(sum(fixed.df$quant0.025[c(1, 4)]),
                   sum(fixed.df$quant0.025[c(2, 8)]),
                   sum(fixed.df$quant0.025[c(5)])), digits=1)) %>%
  mutate(ID1_P = round(c(sum(fixed.df$quant0.025[c(1, 6)]),
                   sum(fixed.df$quant0.025[c(2)]),
                   sum(fixed.df$quant0.025[c(5)])), digits=1)) %>%
  mutate(ID2_P = round(c(sum(fixed.df$quant0.025[c(1, 3, 6)]),
                   sum(fixed.df$quant0.025[c(2, 7)]),
                   sum(fixed.df$quant0.025[c(5)])), digits=1)) %>%
  mutate(ID3_P = round(c(sum(fixed.df$quant0.025[c(1, 4, 6)]),
                   sum(fixed.df$quant0.025[c(2, 8)]),
                   sum(fixed.df$quant0.025[c(5)])), digits=1)) %>%
  gather(Scenario, LB, -Parameter)

ub_fixedeffect.df <- data.frame(Parameter = c("Intercept","Scaled_Elevation", "Scaled_Cover")) %>%
  mutate(ID1_D = round(c(sum(fixed.df$quant0.975[c(1)]),
                   sum(fixed.df$quant0.975[c(2)]),
                   sum(fixed.df$quant0.975[c(5)])), digits=1)) %>%
  mutate(ID2_D = round(c(sum(fixed.df$quant0.975[c(1, 3)]),
                   sum(fixed.df$quant0.975[c(2, 7)]),
                   sum(fixed.df$quant0.975[c(5)])), digits=1)) %>%
  mutate(ID3_D = round(c(sum(fixed.df$quant0.975[c(1, 4)]),
                   sum(fixed.df$quant0.975[c(2, 8)]),
                   sum(fixed.df$quant0.975[c(5)])), digits=1)) %>%
  mutate(ID1_P = round(c(sum(fixed.df$quant0.975[c(1, 6)]),
                   sum(fixed.df$quant0.975[c(2)]),
                   sum(fixed.df$quant0.975[c(5)])), digits=1)) %>%
  mutate(ID2_P = round(c(sum(fixed.df$quant0.975[c(1, 3, 6)]),
                   sum(fixed.df$quant0.975[c(2, 7)]),
                   sum(fixed.df$quant0.975[c(5)])), digits=1)) %>%
  mutate(ID3_P = round(c(sum(fixed.df$quant0.975[c(1, 4, 6)]),
                   sum(fixed.df$quant0.975[c(2, 8)]),
                   sum(fixed.df$quant0.975[c(5)])), digits=1)) %>%
  gather(Scenario, UB, -Parameter)


realeffect.df <- lb_fixedeffect.df %>%
  left_join(ub_fixedeffect.df,
            by = c("Parameter", "Scenario")) %>%
  left_join(mean_fixedeffect.df,
            by = c("Parameter", "Scenario"))


realeffect.df %>%
  mutate(speciesid = substr(Scenario, 1, 3)) %>%
  filter(Parameter == "Scaled_Elevation") %>%
  select(speciesid, Median, UB, LB, Parameter) %>%
  distinct() %>%
  ggplot(aes(y = speciesid, x = Median, xmin = UB, xmax = LB)) +
  geom_errorbarh() +
  theme_project() +
  ggtitle("Scaled Elevation") +
  xlab("Real Elevation Effect - Credible Intervals") +
  ylab("Dominant Species ID") +
  geom_vline(xintercept = 0)

realeffect.df %>%
  filter(Parameter == "Intercept") %>%
  ggplot(aes(y = Scenario, x = Median, xmin = UB, xmax = LB)) +
  geom_errorbarh() +
  theme_project() +
  ggtitle("Site and Dominant Species ID") +
  xlab("Real Intercept Effect - Credible Intervals") +
  ylab("Intercept Scenarios") +
  geom_vline(xintercept = 0)
```

#### Variation Breakdown
```{r}
## How to look at predictions and compare to original???
random <- summary(fit)$hyperpar
# random

randomeffects <- data.frame(hyperparameter = c("Residual", "Transect", "Quadrat:Transect"),
           precision = random[[1]],
           lb = random[[3]],
           ub = random[[5]]) %>%
  mutate(variance = 1/precision,
         varlb = 1/lb,
         varub = 1/ub) %>%
  mutate(totalvar = sum(variance),
         totallb = sum(varlb),
         totalub = sum(varub)) %>%
  mutate(explained = variance/totalvar,
         explainedlb = varlb/totallb,
         explainedub = varub/totalub) %>%
  arrange(desc(explained))

# 
randomeffects %>%
  ggplot(aes(y = hyperparameter, x = variance, xmin = varlb, xmax = varub)) +
  geom_errorbarh() +
  theme_table_pastel() +
  ggtitle("SLA Agg - Random") +
  xlab("Credible Interval") +
  ylab("Hyperparameter")

randomeffects %>%
  mutate(`Variation Explained` = percent(explained)) %>%
  select(hyperparameter, `Variation Explained`)

ggsave(paste0(data_folder, "sla_", "agg","_randomeff.png"), width = 3.5, height = 1.8, dpi = 900)

```


